# Generated by Django 5.0.6 on 2024-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
