# Generated by Django 5.0.6 on 2024-06-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_certificate_fruitreviews_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='fruit_varieties',
            new_name='fruit_varities',
        ),
    ]
